// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Button Link documents
 */
interface ButtonLinkDocumentData {
  /**
   * Text field in *Button Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: button_link.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Page Link field in *Button Link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: button_link.page_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_link: prismic.LinkField;

  /**
   * New Tab field in *Button Link*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: button_link.new_tab
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  new_tab: prismic.BooleanField;

  /**
   * Variant field in *Button Link*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: button_link.variant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<
    "primary" | "secondary" | "outline" | "destructive" | "ghost" | "link",
    "filled"
  >;

  /**
   * Size field in *Button Link*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: button_link.size
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  size: prismic.SelectField<"lg" | "md" | "sm" | "icon">;
}

/**
 * Button Link document from Prismic
 *
 * - **API ID**: `button_link`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ButtonLinkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ButtonLinkDocumentData>,
    "button_link",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | TailoredPaymentsSlice
  | WhyRedstoneSlice
  | PaymentMethodsSlice
  | OnboardSlice
  | IntegrateUsSlice
  | CustomPaymentsSlice
  | SeamlessPaymentsSlice
  | HeroSectionSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the page title
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter SEO meta title
   * - **API ID Path**: page.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter SEO meta description
   * - **API ID Path**: page.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = ButtonLinkDocument | PageDocument;

/**
 * Item in *CustomPayments → Default → Primary → Options*
 */
export interface CustomPaymentsSliceDefaultPrimaryOptionsItem {
  /**
   * Icon field in *CustomPayments → Default → Primary → Options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: custom_payments.default.primary.options[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *CustomPayments → Default → Primary → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: custom_payments.default.primary.options[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *CustomPayments → Default → Primary → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: custom_payments.default.primary.options[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Primary content in *CustomPayments → Default → Primary*
 */
export interface CustomPaymentsSliceDefaultPrimary {
  /**
   * Title field in *CustomPayments → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: custom_payments.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *CustomPayments → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: custom_payments.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Options field in *CustomPayments → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: custom_payments.default.primary.options[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  options: prismic.GroupField<
    Simplify<CustomPaymentsSliceDefaultPrimaryOptionsItem>
  >;
}

/**
 * Default variation for CustomPayments Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomPaymentsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CustomPaymentsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CustomPayments*
 */
type CustomPaymentsSliceVariation = CustomPaymentsSliceDefault;

/**
 * CustomPayments Shared Slice
 *
 * - **API ID**: `custom_payments`
 * - **Description**: CustomPayments
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomPaymentsSlice = prismic.SharedSlice<
  "custom_payments",
  CustomPaymentsSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Hero Image field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Get Started Link field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.get_started_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  get_started_link: prismic.LinkField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *IntegrateUs → Default → Primary*
 */
export interface IntegrateUsSliceDefaultPrimary {
  /**
   * Title field in *IntegrateUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: integrate_us.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *IntegrateUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: integrate_us.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Documentation Link field in *IntegrateUs → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: integrate_us.default.primary.documentation_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  documentation_link: prismic.LinkField;

  /**
   * Image field in *IntegrateUs → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: integrate_us.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for IntegrateUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntegrateUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntegrateUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IntegrateUs*
 */
type IntegrateUsSliceVariation = IntegrateUsSliceDefault;

/**
 * IntegrateUs Shared Slice
 *
 * - **API ID**: `integrate_us`
 * - **Description**: IntegrateUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntegrateUsSlice = prismic.SharedSlice<
  "integrate_us",
  IntegrateUsSliceVariation
>;

/**
 * Primary content in *Onboard → Default → Primary*
 */
export interface OnboardSliceDefaultPrimary {
  /**
   * Title field in *Onboard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: onboard.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Onboard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: onboard.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Onboarding Link field in *Onboard → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: onboard.default.primary.onboarding_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  onboarding_link: prismic.LinkField;
}

/**
 * Default variation for Onboard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OnboardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OnboardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Onboard*
 */
type OnboardSliceVariation = OnboardSliceDefault;

/**
 * Onboard Shared Slice
 *
 * - **API ID**: `onboard`
 * - **Description**: Onboard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OnboardSlice = prismic.SharedSlice<
  "onboard",
  OnboardSliceVariation
>;

/**
 * Item in *PaymentMethods → Default → Primary → Options*
 */
export interface PaymentMethodsSliceDefaultPrimaryOptionsItem {
  /**
   * Icon field in *PaymentMethods → Default → Primary → Options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_methods.default.primary.options[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *PaymentMethods → Default → Primary → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_methods.default.primary.options[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *PaymentMethods → Default → Primary → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_methods.default.primary.options[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Primary content in *PaymentMethods → Default → Primary*
 */
export interface PaymentMethodsSliceDefaultPrimary {
  /**
   * Title field in *PaymentMethods → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_methods.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Options field in *PaymentMethods → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_methods.default.primary.options[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  options: prismic.GroupField<
    Simplify<PaymentMethodsSliceDefaultPrimaryOptionsItem>
  >;
}

/**
 * Default variation for PaymentMethods Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PaymentMethodsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PaymentMethodsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PaymentMethods*
 */
type PaymentMethodsSliceVariation = PaymentMethodsSliceDefault;

/**
 * PaymentMethods Shared Slice
 *
 * - **API ID**: `payment_methods`
 * - **Description**: PaymentMethods
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PaymentMethodsSlice = prismic.SharedSlice<
  "payment_methods",
  PaymentMethodsSliceVariation
>;

/**
 * Primary content in *SeamlessPayments → Default → Primary*
 */
export interface SeamlessPaymentsSliceDefaultPrimary {
  /**
   * Title field in *SeamlessPayments → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seamless_payments.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *SeamlessPayments → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seamless_payments.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Image field in *SeamlessPayments → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: seamless_payments.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for SeamlessPayments Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SeamlessPaymentsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SeamlessPaymentsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SeamlessPayments*
 */
type SeamlessPaymentsSliceVariation = SeamlessPaymentsSliceDefault;

/**
 * SeamlessPayments Shared Slice
 *
 * - **API ID**: `seamless_payments`
 * - **Description**: SeamlessPayments
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SeamlessPaymentsSlice = prismic.SharedSlice<
  "seamless_payments",
  SeamlessPaymentsSliceVariation
>;

/**
 * Primary content in *TailoredPayments → Default → Primary*
 */
export interface TailoredPaymentsSliceDefaultPrimary {
  /**
   * Title field in *TailoredPayments → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tailored_payments.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *TailoredPayments → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tailored_payments.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Image field in *TailoredPayments → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tailored_payments.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TailoredPayments Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TailoredPaymentsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TailoredPaymentsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TailoredPayments*
 */
type TailoredPaymentsSliceVariation = TailoredPaymentsSliceDefault;

/**
 * TailoredPayments Shared Slice
 *
 * - **API ID**: `tailored_payments`
 * - **Description**: TailoredPayments
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TailoredPaymentsSlice = prismic.SharedSlice<
  "tailored_payments",
  TailoredPaymentsSliceVariation
>;

/**
 * Item in *WhyRedstone → Default → Primary → Options*
 */
export interface WhyRedstoneSliceDefaultPrimaryOptionsItem {
  /**
   * Icon field in *WhyRedstone → Default → Primary → Options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: why_redstone.default.primary.options[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *WhyRedstone → Default → Primary → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_redstone.default.primary.options[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *WhyRedstone → Default → Primary → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_redstone.default.primary.options[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Primary content in *WhyRedstone → Default → Primary*
 */
export interface WhyRedstoneSliceDefaultPrimary {
  /**
   * Title field in *WhyRedstone → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_redstone.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *WhyRedstone → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_redstone.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Options field in *WhyRedstone → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: why_redstone.default.primary.options[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  options: prismic.GroupField<
    Simplify<WhyRedstoneSliceDefaultPrimaryOptionsItem>
  >;
}

/**
 * Default variation for WhyRedstone Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyRedstoneSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhyRedstoneSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhyRedstone*
 */
type WhyRedstoneSliceVariation = WhyRedstoneSliceDefault;

/**
 * WhyRedstone Shared Slice
 *
 * - **API ID**: `why_redstone`
 * - **Description**: WhyRedstone
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyRedstoneSlice = prismic.SharedSlice<
  "why_redstone",
  WhyRedstoneSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ButtonLinkDocument,
      ButtonLinkDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CustomPaymentsSlice,
      CustomPaymentsSliceDefaultPrimaryOptionsItem,
      CustomPaymentsSliceDefaultPrimary,
      CustomPaymentsSliceVariation,
      CustomPaymentsSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      IntegrateUsSlice,
      IntegrateUsSliceDefaultPrimary,
      IntegrateUsSliceVariation,
      IntegrateUsSliceDefault,
      OnboardSlice,
      OnboardSliceDefaultPrimary,
      OnboardSliceVariation,
      OnboardSliceDefault,
      PaymentMethodsSlice,
      PaymentMethodsSliceDefaultPrimaryOptionsItem,
      PaymentMethodsSliceDefaultPrimary,
      PaymentMethodsSliceVariation,
      PaymentMethodsSliceDefault,
      SeamlessPaymentsSlice,
      SeamlessPaymentsSliceDefaultPrimary,
      SeamlessPaymentsSliceVariation,
      SeamlessPaymentsSliceDefault,
      TailoredPaymentsSlice,
      TailoredPaymentsSliceDefaultPrimary,
      TailoredPaymentsSliceVariation,
      TailoredPaymentsSliceDefault,
      WhyRedstoneSlice,
      WhyRedstoneSliceDefaultPrimaryOptionsItem,
      WhyRedstoneSliceDefaultPrimary,
      WhyRedstoneSliceVariation,
      WhyRedstoneSliceDefault,
    };
  }
}
